version: '3'
services:
  telegram:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python3", "tg/app.py"]
    volumes:
      - ./.env:/app/.env
      - ./hb.sqlite:/app/hb.sqlite
