version: '3'
services:
  telegram:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python3", "/app/tg/app.py"]
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
